language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
install:
- npm install
env:
  global:
  - secure: ZdO+lHWYNtPhHW+8s/RvY22NdOoOX5feIy93HxvbrZTzljWILEs2WiXbSDyAFQchNjS5ggkhbFvjSklDWocFw9dmhAO90SQzBC5qaLwIw2vcp4cYKmEWIl27orEDUeYzvEN9LVN7vfEDeZqBNf0qHDbkdV0U43JLz/G9tdzpzAB1OOKPvYWkhHHBBMpVvItnPvSNa8+qCPW46rvNP+i2SIbr2lh7pkDkYQxNFNxIeYYv/In09Mj/ZFeDlIO/nfA75874ohRAciF++A9LXBZqs4SNUJfOUHWq1WCifHlH1G1w0RZ73KZp/HBqsiWF2KcACnjHFEQnD+VJUo8TFQX3oMmBKRxA++0SspwalUeADr5Fw7xgiUQfmj6lGuVdHqZTI4Q371Lr0c3/2HUlrXMhxIDLPyRbyN+wcgRByuV1v32GaB7e9rUU3LFV2fs7otBgKyYAA1GYuLZPGth/sDqx2iqhGvMtuEtlX0dlv4OiRtFXYIOvGC6DVzq7fS85f/jsmdkUuV6rfvgkmWjzpy3eKaobFNcjvNDf0LogMe3BUhs52sWDRPDOozKylYyx81Qh+JV0ETx1/tk/2dmwbStPxCyvQTbVOPR8mcYU0aMEBmIcwzSqDBnsCOMAR1JuxP/sRbZFd2jcnIxXQiiURfzJlCuKNMQGHjw741yMdZfJcVg=
  - secure: SEvALkyJvf3Uwp7CBMQ0v7gx37Smz2aAFJNCaFCDPB9yhDwa6BYAATeN9Ti2HjrqMWTvV7k5fJyqH3nDonJcBvJ0KaeOYpXze95U4VL4ZG28v3uzzJlZHArZpwbAECP8NqfjXH58B6xyeJSyN2ZcBar6mf9Rw03HJgI1YLv/cRuYMaLms3ie5U/8yrOxoUb31SS15MLLb6bQ3bhpBRowZYgjup1bXMzDjw+okU1pkg+t3LoLB32XDIEmK4DXETkI7BtaxwOLKubJx1HLuMZlHyVqNPtEiTCxGuVzQ/0RjRUB3/nxU3/Lb0aif3u75MpwKXr16ejMNG1pgbR6irpf3+/pBPcKT8MnaGgPl2qPgWOlFFVeXlhYnneAkOsegOSXsSzHxWP2E+8eIY9K7qrKTCp8OTiSiNZItcM++sv8y/ZFZTNAlnz1b/wKEALKS8DPNyPKtdEMBCf2+uF1wUbxs4Y8Nh28o34v/C8Lh4qirwn3Xu+7bTP69Tc+CZzwJLD1IFwzM/MpT1QfXOol48vHa/oyLOitKoHFsj3k4leGw+uADlOYYl7cGlqenX4HvQn1BV1xr0V8o0L8gppv0pVnBhZ+mC8Zke1AuNP1pE4iqBbbpySxC+KCLdkuiXLXcsIXV0pv4Ilq+BSXeI8UJF6PiiKr8C4xHAguqrUUU8gOEDc=

after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD